Repository versionpress/versionpress, pull requests merged in 2019-05, with the labels that each got.

#1438 Use stripcslashes instead of stripslashes when handling values in sql
  plugins/versionpress/src/Database/SqlQueryParser.php
  plugins/versionpress/tests/Unit/SqlQueryParserTest.php
Labels: bug, scope: core

#1448 Update CloneMergeTest and related to finish #1409
  plugins/versionpress/tests/Workflow/CloneMergeTest.php
Labels: scope: tests

#1437 Update phpmyadmin/sql-parser to 4.3.1
  plugins/versionpress/composer.json
  plugins/versionpress/composer.lock
  plugins/versionpress/src/Database/SqlQueryParser.php
Labels: improvement, scope: core
